### ISSUE TITLE
Use default user, team if set to empty string

### ISSUE THREAD

**Issue by kbernhagen** [FoldingAtHome/fah-client-bastet#31]
If user is set to "", make it "Anonymous"
If team is set to "", make it 0 (zero)

**Comment by jcoffland** [comment]
These are already the defaults.  So the effect is the same.  Are you saying you want to see these values in the frontend config page?

**Comment by kbernhagen** [comment]
I’m saying I can set them to empty strings in the front end, and the client happily accepts them as valid. I think they are also saved to the db as “”.


On Feb 20, 2022, at 12:04 PM, Joseph Coffland ***@***.***> wrote:

﻿
These are already the defaults. So the effect is the same. Are you saying you want to see these values in the frontend config page?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by kbernhagen** [comment]
Maybe the client can just delete user/team if empty, allowing the default to take effect?

**Comment by kbernhagen** [comment]
If user and team are "", the client fails to get an assignment and log is full of exceptions when it tries.

**Comment by jcoffland** [comment]
I've fixed the problem in the backend but the frontend should also prevent these values.

**Comment by kbernhagen** [comment]
The client can get work now, because it will request work using Anonymous, o.

However, the client will never broadcast Anonymous,0 to the frontend. It is always "","".

Restarting the client and frontend does not fix this. Nor does a pause, unpause.

**Comment by kbernhagen** [comment]
The empty values need to actually be removed from the config so the defaults will properly reassert themselves.

**Comment by kbernhagen** [comment]
Or, if there isn't a persistent default in the config db, the client should re-insert the default.
